# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:

  - Name: Orderer
    Domain: results.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5

PeerOrgs:

  - Name: Univ1
    Domain: univ1.results.com
    EnableNodeOUs: true
    Template:
      Count: 2
      # Start: 5
      Hostname: college{{.Index}} # default
    Users:
      Count: 1
  
  - Name: Univ2
    Domain: univ2.results.com
    EnableNodeOUs: true
    Template:
      Count: 2
      Hostname: college{{.Index}}
    Users:
      Count: 1
