
version: '2'

services:

  orderer.results.com:
    container_name: orderer.results.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/results.com/orderers/orderer.results.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/results.com/orderers/orderer.results.com/tls/:/var/hyperledger/orderer/tls
        - orderer.results.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  college0.univ1.results.com:
    container_name: college0.univ1.results.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=college0.univ1.results.com
      - CORE_PEER_ADDRESS=college0.univ1.results.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=college0.univ1.results.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=college1.univ1.results.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=college0.univ1.results.com:7051
      - CORE_PEER_LOCALMSPID=Univ1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ./crypto-config/peerOrganizations/univ1.results.com/peers/college0.univ1.results.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/univ1.results.com/peers/college0.univ1.results.com/tls:/etc/hyperledger/fabric/tls
        - college0.univ1.results.com:/var/hyperledger/production
    ports:
      - 7051:7051

  college1.univ1.results.com:
    container_name: college1.univ1.results.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=college1.univ1.results.com
      - CORE_PEER_ADDRESS=college1.univ1.results.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=college1.univ1.results.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=college1.univ1.results.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=college0.univ1.results.com:7051
      - CORE_PEER_LOCALMSPID=Univ1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/univ1.results.com/users/User1@univ1.results.com/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/univ1.results.com/peers/college1.univ1.results.com/tls/ca.crt
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ./crypto-config/peerOrganizations/univ1.results.com/peers/college1.univ1.results.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/univ1.results.com/peers/college1.univ1.results.com/tls:/etc/hyperledger/fabric/tls
        - college1.univ1.results.com:/var/hyperledger/production

    ports:
      - 8051:8051

  college0.univ2.results.com:
    container_name: college0.univ2.results.com
    extends:  
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=college0.univ2.results.com
      - CORE_PEER_ADDRESS=college0.univ2.results.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=college0.univ2.results.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=college0.univ2.results.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=college1.univ2.results.com:10051
      - CORE_PEER_LOCALMSPID=Univ2MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/univ2.results.com/users/Admin@univ2.results.com/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/univ2.results.com/peers/college0.univ2.results.com/tls/ca.crt
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ./crypto-config/peerOrganizations/univ2.results.com/peers/college0.univ2.results.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/univ2.results.com/peers/college0.univ2.results.com/tls:/etc/hyperledger/fabric/tls
        - college0.univ2.results.com:/var/hyperledger/production
    ports:
      - 9051:9051

  college1.univ2.results.com:
    container_name: college1.univ2.results.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=college1.univ2.results.com
      - CORE_PEER_ADDRESS=college1.univ2.results.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=college1.univ2.results.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=college1.univ2.results.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=college0.univ2.results.com:9051
      - CORE_PEER_LOCALMSPID=Univ2MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/univ2.results.com/users/User1@univ2.results.com/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/univ2.results.com/peers/college1.univ2.results.com/tls/ca.crt
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ./crypto-config/peerOrganizations/univ2.results.com/peers/college1.univ2.results.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/univ2.results.com/peers/college1.univ2.results.com/tls:/etc/hyperledger/fabric/tls
        - college1.univ2.results.com:/var/hyperledger/production
    ports:
      - 10051:10051
